### ISSUE TITLE
Screen goes blank when attempting to rotate a full 180 degrees

### ISSUE THREAD

**Issue by emanguy** [jimmy00784/InspironAutoRotateService#1]
When rotating my Inspiron 7000 series 13'' 2-in-1, I notice that the display does not turn back on if you rotate from normal landscape to inverted landscape while the service is sleeping. I'll see if I can find a fix and provide a pull request.

**Comment by lalanikarim** [comment]
Thanks Evan @emanguy

**Comment by lalanikarim** [comment]
Pull request merged.
Thanks @emanguy

**Comment by emanguy** [comment]
No problem!
