### ISSUE TITLE
More detailed instruction

### ISSUE THREAD

**Issue by draosh** [jimmy00784/InspironAutoRotateService#4]
Dear Karim!
Thank you for your contribution! I tried it on my Dell Inspiron 13 7347 under Antergos, but unfortunately have had no result. I suppose, I missed something because I'm new to Arch. I created the folder /systemd/user in ~/.config, because there had been none. I put there inspironAutoRotateScreen.service. I edited the string in user.conf the way you put. Then tried to start the service via your commands but no success. Neither via executing the scripts in terminal. Could you specify in steps how it should be implemented and whether some kernel modules should be enacted (I am not sure that everything of that kind installed from the box)?
Bests!

**Comment by lalanikarim** [comment]
Hi @draosh 
Firstly, were you able to verify if the inspironRotateScreen and inspironReadSensor scripts work correctly?
Once that is done, then it's a matter of installing a systemd service for the local user.
Regards

**Comment by draosh** [comment]
If by verifying you mean running them, then yes, I ran them in terminal, but no rotation and no change. 
Here is the output of the RotateScreen:
Dell Inspiron 2-in-1 Screen Rotation Script for Linux
Tested successfully with Dell Inspiron 13 i7347 2-in-1 Laptop

usage: inspironRotateScreen [option]
options
        left            - rotates screen 90 degrees to the left from the normal mode
        right           - rotates screen 90 degrees to the right from the normal mode
        inverted        - rotates screen 180 degrees from the normal mode
        normal          - resets the screen orientation to normal mode

Script with option could be attached to Keyboard shortcuts as well as Operating System Events
The intention is to apply the script to system events that respond to the laptops internal gyroscope to automatically rotate the screen

Author: Karim Lalani - jimmy00784@gmail.com

This is the output of the ReadSensor:
at: /in_accel_scale: No such file or directory
cat: /in_accel_x_raw: No such file or directory
cat: /in_accel_y_raw: No such file or directory
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
Then - that it is expecting an unary operator in strings 26, 30, 34, 48.

**Comment by lalanikarim** [comment]
@draosh 
For inspironRotateScreen, provide the option argument of left, right, or inverted to test rotation.
`./inspironRotateScreen inverted`
To change rotation back to normal, use the option argument of normal.
`./inspironRotateScreen normal`

The output from ReadSensor is because you didn't provide sensor directory argument that is needed.
The sensor directory is one of iio:device* directories in the /sys/bus/iio/devices folder.
iio:device* directories have a file called "name" in them. Check those and find the directory where the name file has text "accel_3d" in it. That is the directory you must pass to the inspironReadSensor.
`./inspironReadSensor /sys/bus/iio/devices/iio\:device1`
You should see the output as "normal" which is the current expected rotation of your screen.
Let me know if this helps

**Comment by draosh** [comment]
The part with RotateScreen worked. A kind of progress The ReadSensor sais "flat" both in normal and inverted orientations.

**Comment by lalanikarim** [comment]
@draosh You should see normal if screen is upright position, and inverted if your laptop is setup in "tent" position. flat should appear when the screen is flat parallel to the ground.
Do you see the below files "in_accel_x_raw" and "in_accel_y_raw"?
If so, read from those files 4 times and observe the values. They should vary with every time you read from them.
If you are reading only 0 from them every time, then there might be an issue with your setup.

**Comment by draosh** [comment]
Sorry for a stupid question, but does "read" mean a certain command in terminal or just openning them in the text editor? I am not advanced in terminology. Openning gives 0 all the time.

**Comment by lalanikarim** [comment]
@draosh No worries. You can use the cat command to read those files, like:
`cat /sys/bus/iio/devices/iio\:device1/in_acces_x_raw`
If you are getting 0 all the time, that might mean that your sensor isn't triggering for some reason.

**Comment by draosh** [comment]
Thank you for understanding! Meanwhile, still 0. I haven't said that this time I am doing it under ubuntu. Could the issue with triggering be due to this and should I try the same when boot into arch?

**Comment by lalanikarim** [comment]
@draosh I've only tested this on Archlinux and I am not sure what additional steps might be required to get it to function under Ubuntu or other distributions. If it is an option, please test this under Arch to see if you observe any different behavior.

**Comment by draosh** [comment]
Ok, I'll let you know tomorrow or in two days maximum. I would appreciate if you will stay in touch for a while. Your instructions are very helpful. Thank you!

**Comment by lalanikarim** [comment]
@draosh Sure. Anytime.

**Comment by draosh** [comment]
Hi. Arch gives the same results. I'm going to check if the sensor disconnected, because Win 10 in the tablet mode doesn't do rotation either. However, it couldn't be broken from the very beginning, because 2 years ago it have worked both in Windows 8 and in Ubuntu 14 (I enabled it then with yoga-laptop-master, which is still somewhere in the net, I gues).

**Comment by lalanikarim** [comment]
@draosh keep me posted on what you find. At this time it appears that the issue might be specific to your laptop. I'll close the issue however, feel free to reach out of you find out otherwise.
